# Generated by Django 2.0 on 2022-03-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220315_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_complete_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Seat selection completion time'),
        ),
    ]
