# Generated by Django 2.0 on 2022-03-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_seat_seat_complete_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ticket_number',
            new_name='order_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ticket_price',
            new_name='order_number_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ticket_type',
            new_name='order_number_type',
        ),
    ]
