# Generated by Django 2.0 on 2022-03-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_seat_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number_price',
            new_name='order_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_number_type',
            new_name='order_type',
        ),
    ]
