# Generated by Django 2.0 on 2022-03-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220316_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oder_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='order key'),
        ),
    ]
