# Generated by Django 2.0 on 2022-03-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_order_oder_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oder_key',
            new_name='order_key',
        ),
    ]
