# Generated by Django 2.0 on 2022-03-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220316_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Departure_station',
            field=models.CharField(max_length=50, verbose_name='Departure_station'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_station',
            field=models.CharField(max_length=50, verbose_name='destination_station'),
        ),
    ]
